name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - "main"
      - "task/**"

permissions:
  contents: read
  actions: read
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_OPTIONS: --max_old_space_size=4096
  CI: true

jobs:
  backend-lint:
    name: backend-lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: backend/package-lock.json
      - name: Install dependencies
        working-directory: backend
        run: npm ci
      - name: Lint
        working-directory: backend
        run: npm run lint

  backend-test:
    name: backend-test
    runs-on: ubuntu-latest
    needs: backend-lint
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: backend/package-lock.json
      - name: Install dependencies
        working-directory: backend
        run: npm ci
      - name: Run tests
        working-directory: backend
        run: npm test
      - name: Generate coverage
        working-directory: backend
        run: npm run test:coverage
      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: |
            backend/coverage
            backend/coverage/lcov.info
          if-no-files-found: error
          retention-days: 14

  frontend-lint:
    name: frontend-lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        working-directory: frontend
        run: npm ci
      - name: Lint
        working-directory: frontend
        run: npm run lint

  admin-build:
    name: admin-build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: admin/package-lock.json
      - name: Install dependencies
        working-directory: admin
        run: npm ci
      - name: Build
        working-directory: admin
        run: npm run build
      - name: Upload admin dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: admin-dist
          path: admin/dist
          if-no-files-found: error
          retention-days: 14


